# Generated by Django 2.1.2 on 2018-11-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member_dbdm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32, unique=True)),
                ('user_pw', models.CharField(max_length=32)),
                ('user_name', models.CharField(max_length=32)),
                ('user_address', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=64)),
                ('join_date', models.DateTimeField(verbose_name='date joined')),
            ],
        ),
    ]
